{"uuid": "00ebd591-9608-4da8-aacf-f980e494dde6", "children": ["36f4d3d9-604e-46ea-ad05-38dd6a2dcade"], "befores": [{"name": "open_app", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.ecloud.hobay' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command 'D:\\\\android-sdk-windows\\\\platform-tools\\\\adb.exe -P 5037 -s eba33135 shell am start -W -n com.ecloud.hobay/.function.splash.SplashActivity -S' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability\n\n", "trace": "  File \"D:\\Python38\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 915, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Pycharm_workspace\\APPV1.0\\TestCases\\conftest.py\", line 37, in open_app\n    driver = BaseDriver().base_driver(device=request.param)\n  File \"D:\\Pycharm_workspace\\APPV1.0\\Common\\BaseDriver.py\", line 29, in base_driver\n    driver = webdriver.Remote(\"http://{0}:{1}/wd/hub\".format(i[\"server_url\"], i[\"server_port\"]),\n  File \"D:\\Python38\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 151, in __init__\n    super().__init__(\n  File \"D:\\Python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"D:\\Python38\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 225, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"D:\\Python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Python38\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1597060176596, "stop": 1597060208923}], "start": 1597060176596, "stop": 1597060209296}